# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/img_data_rom/img_data_rom.xci
# IP: The module: 'img_data_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/img_data_rom/img_data_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_data_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/img_data_rom/img_data_rom.xci
# IP: The module: 'img_data_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/img_data_rom/img_data_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_data_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
