# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/addr_add/addr_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==addr_add || ORIG_REF_NAME==addr_add} -quiet] -quiet

# IP: ip/addr_mult/addr_mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==addr_mult || ORIG_REF_NAME==addr_mult} -quiet] -quiet
