# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.cache/wt [current_project]
set_property parent.project_path C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Smvar/Desktop/Project/reconfigure_test/AI_Mate_IP_repo
  c:/Users/Smvar/Desktop/one_channal_cache_clk/AI_Mate/AI_Mate/AI_Mate_IP_repo
  {c:/Users/Smvar/Desktop/PS_AI IP/PS_AI IP/processing_system7_v5_5}
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
set src_rc [catch { 
  puts "source C:/Users/Smvar/Desktop/Project/reconfigure_test/ip_patch/process_control/synthesis_pre.tcl"
  source C:/Users/Smvar/Desktop/Project/reconfigure_test/ip_patch/process_control/synthesis_pre.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script C:/Users/Smvar/Desktop/Project/reconfigure_test/ip_patch/process_control/synthesis_pre.tcl failed"
  return -code error
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/sv/mna_itf.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/image_make/image_make_top.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/image_make/image_make_ctrl.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nearest_upsample/nearest_ctrl.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nearest_upsample/nearest_top.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/nms_ctrl.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/nms_cdc_fifo.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/nms_top.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/norm_wrapper.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/segpost_top.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/ftmp_rdma.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/remap_top.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/remap_ctrl.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/grid_rdma.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/ddr_ritcn_remap.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/n2w_remap.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/grid_trans.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/remap.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/remap_bram.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/w2n_remap.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/ftmp_wdma.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/remap/bilinear_remap.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/gen_b_done.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/argmax2d_top.sv
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/argmax2d_ctrl.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/AVR/avr_frs.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/AVR/avr_brs.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/AVR/avr_rs.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/image_make/cut_fixed.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/image_make/img_padding.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/image_make/image_data_processing.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/image_make/pulse_cross.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nearest_upsample/nearest_upsample_wdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nearest_upsample/nearest_upsample_rdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nearest_upsample/addr_gen.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/iou_cu.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/n2w_bwc_addr.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/avr_rb_double.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/iou_dma_bram.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/nms_rdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/nms_bram.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/nms/nms_wdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/defer_unit.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/inst_ctrl.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/norm_ctrl.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/norm_cell.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/variance_cell.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/parallel_to_serial.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/cdc_process.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/serial_to_parallel.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/carmack.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/norm_dma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/norm/norm_core.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/customop_dwdc/collecting_fifo.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/sel.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/segpost_ctrl.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/bcmp.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/max_cmp.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/cmp.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/segpost_wdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/n2w_segpost.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/addrgen.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/conf_buffer.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/bcacu.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/upsample.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/argmax.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/idx_buffer.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/obuffer.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/bilinear.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/one_pixel.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/segpost/coordgen.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/AVR/avr_rb.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/argmax2d_cmp.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/axis_fifo_cdc64.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/argmax2d_wdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/axis_fifo_cdc32.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/argmax2d_rdma.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/axis_fifo.v
  C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/rtl/hardop/argmax2d/cmp_argmax2d.v
}
read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/addr_add/addr_add.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/addr_mult/addr_mult.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/mna_idfifo/mna_idfifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/mna_idfifo/mna_idfifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/mna_idfifo/mna_idfifo_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/sub/sub_data.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/mult_data/mult_data.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w616d64_fifo/w616d64_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w616d64_fifo/w616d64_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w616d64_fifo/w616d64_fifo_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w1280_d512/w1280_d512.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w1280_d512/w1280_d512_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/cdc_fifo_nms_base/cdc_fifo_nms_base.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/cdc_fifo_nms_base/cdc_fifo_nms_base.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/cdc_fifo_nms_base/cdc_fifo_nms_base_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/cdc_fifo_nms_base/cdc_fifo_nms_base_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/mult_16_16/mult_16_16.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w16_d512/w16_d512.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/w16_d512/w16_d512_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/mult_24_16/mult_24_16.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/sub_16_16/sub_16_16.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/sub_32_32/sub_32_32.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/dsp48_mac/dsp48_mac.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/dsp48_mac/dsp48_mac_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/add_s74_s72/add_s74_s72.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/add_s74_s72/add_s74_s72_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w24d32_dram/fifo_w24d32_dram.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w24d32_dram/fifo_w24d32_dram.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w24d32_dram/fifo_w24d32_dram_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w24_dram/fifo_w24_dram.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w24_dram/fifo_w24_dram.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w24_dram/fifo_w24_dram_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w15/fifo_w15.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w15/fifo_w15.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w15/fifo_w15_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w28d1k/fifo_w28d1k.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w28d1k/fifo_w28d1k.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w28d1k/fifo_w28d1k_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w976d16/fifo_w976d16.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w976d16/fifo_w976d16.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w976d16/fifo_w976d16_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w512/fifo_w512.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w512/fifo_w512.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w512/fifo_w512_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/add_32_32/add_32_32.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fp16_mult/fp16_mult.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fp16_mult/fp16_mult_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fp_to_fix/fp_to_fix.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fp_to_fix/fp_to_fix_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/addsub_int/addsub_int.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/addsub_int/addsub_int_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/add_int64/add_int64.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/add_int64/add_int64_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fp16_sub/fp16_sub.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fp16_sub/fp16_sub_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/mult_32x25/mult_32x25.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/mult_32x25/mult_32x25_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/add_unsigned/add_unsigned.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fix_to_float/fix_to_float.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fix_to_float/fix_to_float_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w64d1k/fifo_w64d1k.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w64d1k/fifo_w64d1k.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w64d1k/fifo_w64d1k_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w25/fifo_w25.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w25/fifo_w25.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w25/fifo_w25_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w15d1k/fifo_w15d1k.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w15d1k/fifo_w15d1k.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w15d1k/fifo_w15d1k_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_async_fifo/sp_async_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_async_fifo/sp_async_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_async_fifo/sp_async_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_async_fifo/sp_async_fifo_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/idx_mem/idx_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/idx_mem/idx_mem_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/bdsp/bdsp.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/bdsp/bdsp_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/lbdsp/lbdsp.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/lbdsp/lbdsp_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/conf_mem/conf_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/conf_mem/conf_mem_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_rddr_fifo/sp_rddr_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_rddr_fifo/sp_rddr_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/segpost/sp_rddr_fifo/sp_rddr_fifo_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w33d1k/fifo_w33d1k.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w33d1k/fifo_w33d1k.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w33d1k/fifo_w33d1k_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/add_int15/add_int15.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w23/fifo_w23.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w23/fifo_w23.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w23/fifo_w23_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w36d512/fifo_w36d512.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w36d512/fifo_w36d512.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w36d512/fifo_w36d512_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w36d1k/fifo_w36d1k.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w36d1k/fifo_w36d1k.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/norm/fifo_w36d1k/fifo_w36d1k_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/mult_22_16/mult_22_16.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/mult_22_16/mult_22_16_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/add_38_38/add_38_38.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/mult_s_26_16/mult_s_26_16.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/w514d512_fifo/w514d512_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/w514d512_fifo/w514d512_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/w514d512_fifo/w514d512_fifo_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/add_s_32_32/add_s_32_32.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/ftmp_dpram/ftmp_dpram.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/ftmp_dpram/ftmp_dpram_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/remap/add_39_39/add_39_39.xci

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo/base_axis_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo/base_axis_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo/base_axis_fifo_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc32/base_axis_fifo_cdc32.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc32/base_axis_fifo_cdc32.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc32/base_axis_fifo_cdc32_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc32/base_axis_fifo_cdc32_ooc.xdc]

read_ip -quiet C:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64.xci
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Smvar/Desktop/Project/reconfigure_test/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top nms_top -part xc7z100ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nms_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nms_top_utilization_synth.rpt -pb nms_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
