# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/segpost/lbdsp/lbdsp.xci
# IP: The module: 'lbdsp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/segpost/lbdsp/lbdsp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lbdsp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/segpost/lbdsp/lbdsp.xci
# IP: The module: 'lbdsp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/segpost/lbdsp/lbdsp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lbdsp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
