# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64.xci
# IP: The module: 'base_axis_fifo_cdc64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axis_fifo_cdc64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axis_fifo_cdc64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axis_fifo_cdc64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64.xci
# IP: The module: 'base_axis_fifo_cdc64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axis_fifo_cdc64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axis_fifo_cdc64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_workspace/wangyl/prj_2024/0830/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/base_axis_fifo_cdc64/base_axis_fifo_cdc64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axis_fifo_cdc64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
