# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/remap/mult_22_16/mult_22_16.xci
# IP: The module: 'mult_22_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/remap/mult_22_16/mult_22_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_22_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/remap/mult_22_16/mult_22_16.xci
# IP: The module: 'mult_22_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_workspace/luowei/release_fpga/wyl_finnal/0731/one_input_wk_display_custop0_24073104/AI_Mate_IP/ps_in.srcs/sources_1/ip/remap/mult_22_16/mult_22_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_22_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
